// <auto-generated />
namespace Org.Carfh.Courseware.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class InitialModifs : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(InitialModifs));
        
        string IMigrationMetadata.Id
        {
            get { return "201602280517295_InitialModifs"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
